# Generated by Django 3.0.6 on 2020-12-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pose',
            name='base_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pose',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pose',
            name='sanskrit_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
